name: Deploy to AliyunOSS
on: [push]
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build Project
        run: npm install && npm run build

      - name: Deploy OSS
        uses: taixw2/deploy-aliyun-oss@v1
        with:
          # aliyun config
          region: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.BUCKET }}
          secure: true
          # deploy config
          entry: docs/.vuepress/dist/**/* # glob pattern
          remote-dir: /
          path-rewrite: ^docs/.vuepress/dist/
